[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MLsystem"
version = "0.1.0"
dependencies = [
    "pytorch-lightning",
    "hydra-core",
]

[tool.setuptools]
package-dir = {"MLsystem" = "."}
